---

- name: setup apt-cacher-ng proxy
  template: src=01proxy.j2 dest=/etc/apt/apt.conf.d/01proxy
  register: new_apt_cacher

- name: install required packages to add havana repository
  apt: name={{ item }} state=installed update_cache=yes #cache_valid_time=3600
  with_items: ubuntu_packages
  when: new_apt_cacher.changed