---

#
# Stop portmapper
# 

- name: ensure portmap is not running
  service: name=portmap state=stopped enabled=no
  ignore_errors: true

#
# NTP
# 

- include: debian_ntp.yml

#
# Havana repository
# 

- include: debian_openstack_repository.yml

