# file: postgresql/tasks/extensions/contrib.yml

- name: PostgreSQL | Extensions | Make sure the postgres contrib extensions are installed
  apt:
    name: "postgresql-contrib-{{postgresql_version}}"
    state: present
  notify:
    - restart postgresql

