---

#
# First setup a package_cache, especially when using
# your laptop and Vagrant
#

- hosts: package_cache
  roles:
  - package_cache

- hosts: 
  - all
  roles:
  - common

- hosts:
  - lbssl
  roles:
  - lbssl

- hosts:
  - proxy
  - storage
  - package_cache
  roles:
    - swift_common

- hosts: 
    - swiftclient
  roles:
    - swiftclient

- hosts: 
   - authentication
  roles:
   - authentication

- hosts: 
  - proxy
  roles:
  - proxy

#
# I would have expected serial to work here, and
# to be the right way to do it but at the time I
# tried received "too many files open" errors.
#

- hosts:
  - storage
  serial: 1
  roles:
  - storage

#
# These are not so much roles as starting services
# though also includes distributing the ring files.
# 

- hosts: 
  - proxy
#  vars_file:
#  - include: vars/{{ansible_os_family}}.yml
  tasks:
  - include: start_proxy.yml

- hosts:
  - storage
#  vars_file:
#  - include: vars/{{ansible_os_family}}.yml
  tasks:
  - include: start_storage.yml

#
# Probably best to run these on their own?
#

#- include: tests/tests.yml