---
  - name: "Ensure basic packages are installed"
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
        - libpq-dev
        - git
        - vim
        - rsync
        - sudo
        - python-pip
        - python-dev
        - python-apt
        - python-pycurl
        - python-psycopg2

  - name: "Ensure owncloud dependencies are installed"
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
        - php5
        - php5-pgsql
        - php5-gd
        - php5-json
        - postgresql
        - php5-ldap

  # - name: "Ensure php5 configuration limits are set"
  - ini_file: dest=/etc/php5/apache2/php.ini section=PHP option=max_execution_time value=200
  - ini_file: dest=/etc/php5/apache2/php.ini section=PHP option=upload_max_filesize value=16G
  - ini_file: dest=/etc/php5/apache2/php.ini section=PHP option=post_max_size value=16G
  - ini_file: dest=/etc/php5/apache2/php.ini section=PHP option=memory_limit value=8G

  - name: "Setting apache2 vhost definition"
    template: src=apache2-owncloud dest=/etc/apache2/{{ item }}
    with_items:
        - sites-available/owncloud
        - sites-enabled/owncloud

  - name: "Include OwnCloud official package repos"
    include: owncloud_repo.yml

  - name: "Create data storage folder outside webroot (as specified in (auto)config.php)"
    file: dest=/mnt/owncloud/data mode=775 owner=www-data group=www-data state=directory
  
  - name: "Install ownCloud"
    apt: name=owncloud state=present force=yes

  - name: "Adjust Apache docroot"
    replace: dest=/etc/apache2/sites-enabled/000-default.conf regexp='DocumentRoot /var/www/html' replace='DocumentRoot /var/www/owncloud'
    notify: restart apache2
   
  - name: "Deploy autoconfig.php"
    template: src=autoconfig.php.j2 dest=/var/www/owncloud/config/autoconfig.php

  - name: "Adjust permissions"
    file: path=/var/www/owncloud state=directory owner=www-data group=www-data recurse=true

  - name: "Add owncloud Postgresql database credentials"
    include: postgresql.yml
    notify:
        - restart apache2
        - restart postgresql
